# -*- coding: utf-8 -*-
"""Copy of Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBh7JGygKFtFUONw-0JZxnn4kV54JOUl

#AI Resume Screening System

#INSTALL DEPENDENCIES
"""

!pip install pdfplumber nltk scikit-learn pandas numpy

!pip install gradio

"""#IMPORT LIBRARIES"""

import pdfplumber
import nltk
import re
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

import gradio as gr
import pdfplumber
import re
import nltk
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

"""#DOWNLOAD NLP RESOURCES"""

nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

"""#UPLOAD RESUME PDF"""

from google.colab import files

uploaded = files.upload()

"""#EXTRACT TEXT FROM PDF"""

resume_file = list(uploaded.keys())[0]

resume_text = ""

with pdfplumber.open(resume_file) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if text:
            resume_text += text

print(resume_text[:1000])

"""#SAMPLE JOB DESCRIPTION"""

job_description = """
We are looking for an AI/ML Intern with skills in Python,
Machine Learning, Deep Learning, TensorFlow, SQL,
Data Analysis, Pandas, NumPy.
"""

"""#TEXT CLEANING FUNCTION"""

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z ]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

resume_clean = clean_text(resume_text)
jd_clean = clean_text(job_description)

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z ]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

"""#CREATE TRAINING DATA"""

data = {
    "text": [
        "python machine learning tensorflow deep learning data science",
        "sales marketing communication business management",
        "python pandas numpy sql data analysis machine learning",
        "hr recruitment communication leadership management",
        "deep learning neural networks tensorflow pytorch",
        "finance accounting excel budgeting analysis"
    ],
    "label": [1, 0, 1, 0, 1, 0]
}

import pandas as pd

df = pd.DataFrame(data)
df["clean_text"] = df["text"].apply(clean_text)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["clean_text"])
y = df["label"]

model = LogisticRegression()
model.fit(X, y)

"""#FEATURE EXTRACTION (TF-IDF)"""

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_text"])
y = df["label"]

"""#TRAIN ML MODEL"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

"""#MODEL EVALUATION"""

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""#PREDICT RESUME FIT"""

resume_vec = vectorizer.transform([resume_clean])

prediction = model.predict(resume_vec)[0]

print("===== RESULT =====")

if prediction == 1:
    print("✅ Strong Technical Fit for AI/ML Role")
else:
    print("❌ Weak Fit for AI/ML Role")

"""#BONUS SCORE"""

prob = model.predict_proba(resume_vec)[0][1] * 100

print(f"Match Confidence Score: {prob:.2f}%")

"""#GRADIO INTERFACE"""

def analyze_resume(file, job_desc):

    # extract pdf text
    resume_text = ""
    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:
            if page.extract_text():
                resume_text += page.extract_text()

    # clean
    resume_clean = clean_text(resume_text)

    # vectorize
    vec = vectorizer.transform([resume_clean])

    # prediction
    prob = model.predict_proba(vec)[0][1] * 100
    pred = model.predict(vec)[0]

    # output
    if pred == 1:
        result = "✅ Strong Match for AI/ML Role"
    else:
        result = "❌ Weak Match for AI/ML Role"

    return f"""
    📊 MATCH SCORE: {prob:.2f}%

    {result}

    📄 Resume Preview:
    {resume_text[:800]}
    """

"""#LAUNCH UI"""

interface = gr.Interface(
    fn=analyze_resume,
    inputs=[
        gr.File(label="Upload Resume (PDF)"),
        gr.Textbox(label="Job Description")
    ],
    outputs=gr.Markdown(),
    title="AI Resume Screening System",
    description="Upload resume and check ML-based job fit"
)

interface.launch()

